-- ============================================
-- BOXME FORECAST MVP - DATABASE SCHEMA
-- ============================================

-- Orders history (populated from WMS or fake data)
CREATE TABLE IF NOT EXISTS orders_history (
    id TEXT PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    order_date TEXT NOT NULL,
    order_time TEXT NOT NULL,
    fulfillment_center_id TEXT NOT NULL,
    customer_id TEXT,
    marketplace TEXT,
    product_group INTEGER,
    sku_complexity TEXT,
    service_level TEXT,
    shipping_carrier TEXT,
    num_items INTEGER,
    is_delayed_allowed INTEGER DEFAULT 0,
    sla_deadline TEXT,
    completion_time TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

-- Workforce history (populated from OPS or fake data)
CREATE TABLE IF NOT EXISTS workforce_history (
    id TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    shift TEXT,
    work_type TEXT,
    staff_type TEXT,
    staff_level INTEGER,
    product_group INTEGER,
    staff_count INTEGER,
    hours_worked REAL,
    orders_processed INTEGER,
    points_earned REAL,
    cost REAL,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Productivity standards (configuration)
CREATE TABLE IF NOT EXISTS productivity_standards (
    id TEXT PRIMARY KEY,
    staff_type TEXT NOT NULL,
    staff_level INTEGER NOT NULL,
    product_group INTEGER NOT NULL,
    orders_per_hour REAL,
    cost_per_hour REAL,
    cost_per_point REAL,
    notes TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(staff_type, staff_level, product_group)
);

-- Calendar events (peak days, holidays)
CREATE TABLE IF NOT EXISTS calendar_events (
    id TEXT PRIMARY KEY,
    event_date TEXT NOT NULL,
    event_type TEXT,
    event_name TEXT,
    is_peak INTEGER DEFAULT 0,
    expected_multiplier REAL,
    notes TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(event_date, event_type)
);

-- Customer forecasts (if customers provide)
CREATE TABLE IF NOT EXISTS customer_forecasts (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL,
    forecast_date TEXT NOT NULL,
    submitted_at TEXT DEFAULT (datetime('now')),
    forecasted_orders INTEGER,
    actual_orders INTEGER,
    accuracy_score REAL,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(customer_id, forecast_date)
);

-- Daily forecasts (generated by models)
CREATE TABLE IF NOT EXISTS daily_forecasts (
    id TEXT PRIMARY KEY,
    forecast_date TEXT NOT NULL,
    generated_at TEXT DEFAULT (datetime('now')),
    model_version TEXT,
    baseline_forecast INTEGER,
    ml_forecast INTEGER,
    ml_confidence REAL,
    customer_forecast INTEGER,
    customer_weight REAL,
    final_forecast INTEGER,
    lower_bound INTEGER,
    upper_bound INTEGER,
    actual_orders INTEGER,
    mape REAL,
    is_peak_day INTEGER DEFAULT 0,
    peak_multiplier REAL,
    notes TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(forecast_date)
);

-- Workforce recommendations
CREATE TABLE IF NOT EXISTS workforce_recommendations (
    id TEXT PRIMARY KEY,
    forecast_id TEXT,
    forecast_date TEXT NOT NULL,
    pick_hours REAL,
    pack_hours REAL,
    moving_hours REAL,
    return_hours REAL,
    total_hours REAL,
    boxme_staff_needed INTEGER,
    seasonal_staff_needed INTEGER,
    veteran_staff_needed INTEGER,
    total_staff_needed INTEGER,
    available_boxme INTEGER,
    available_seasonal INTEGER,
    available_veteran INTEGER,
    gap_total INTEGER,
    contractor_recruitment_needed INTEGER,
    estimated_cost REAL,
    contractor_bonus_cost REAL,
    meal_cost REAL,
    total_cost REAL,
    alert_level TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (forecast_id) REFERENCES daily_forecasts(id)
);

-- Hiring alerts
CREATE TABLE IF NOT EXISTS hiring_alerts (
    id TEXT PRIMARY KEY,
    forecast_date TEXT NOT NULL,
    alert_date TEXT NOT NULL,
    days_until_event INTEGER,
    contractors_needed INTEGER,
    alert_level TEXT,
    status TEXT DEFAULT 'pending',
    acknowledged_by TEXT,
    acknowledged_at TEXT,
    notes TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Product groups
CREATE TABLE IF NOT EXISTS product_groups (
    id INTEGER PRIMARY KEY,
    group_name TEXT,
    description TEXT,
    examples TEXT
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_orders_date ON orders_history(order_date);
CREATE INDEX IF NOT EXISTS idx_orders_fc ON orders_history(fulfillment_center_id);
CREATE INDEX IF NOT EXISTS idx_orders_product_group ON orders_history(product_group);
CREATE INDEX IF NOT EXISTS idx_workforce_date ON workforce_history(date);
CREATE INDEX IF NOT EXISTS idx_forecasts_date ON daily_forecasts(forecast_date);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON hiring_alerts(status, alert_date);

-- ============================================
-- SEED CONFIGURATION DATA
-- ============================================

-- Product groups
INSERT OR IGNORE INTO product_groups (id, group_name, description, examples) VALUES
(1, 'Nhóm 1', 'Mỹ phẩm SG-BD', 'Cosmetics, skincare'),
(2, 'Nhóm 2', 'Thực phẩm, đồ dùng gia đình SG-BD', 'Food, household items'),
(3, 'Nhóm 3', 'Sữa bỉm, cồng kềnh SG-BD', 'Baby products, bulky items'),
(4, 'Nhóm 4', 'MIX: Sữa, bỉm, các loại khác', 'Mixed categories');

-- Productivity standards (all combinations)
-- Boxme staff
INSERT OR IGNORE INTO productivity_standards (id, staff_type, staff_level, product_group, orders_per_hour, cost_per_hour, cost_per_point) VALUES
('ps-boxme-1-1', 'boxme', 1, 1, 40, 25000, 625),
('ps-boxme-1-2', 'boxme', 1, 2, 40, 25000, 625),
('ps-boxme-1-3', 'boxme', 1, 3, 40, 25000, 625),
('ps-boxme-1-4', 'boxme', 1, 4, 35, 25000, 714),
('ps-boxme-2-1', 'boxme', 2, 1, 35, 22000, 629),
('ps-boxme-2-2', 'boxme', 2, 2, 30, 22000, 733),
('ps-boxme-2-3', 'boxme', 2, 3, 30, 22000, 733),
('ps-boxme-2-4', 'boxme', 2, 4, 25, 22000, 880),
('ps-boxme-3-1', 'boxme', 3, 1, 30, 20000, 667),
('ps-boxme-3-2', 'boxme', 3, 2, 20, 20000, 1000),
('ps-boxme-3-3', 'boxme', 3, 3, 20, 20000, 1000),
('ps-boxme-3-4', 'boxme', 3, 4, 20, 20000, 1000);

-- Seasonal staff
INSERT OR IGNORE INTO productivity_standards (id, staff_type, staff_level, product_group, orders_per_hour, cost_per_hour, cost_per_point) VALUES
('ps-seasonal-1-1', 'seasonal', 1, 1, 30, 22000, 733),
('ps-seasonal-1-2', 'seasonal', 1, 2, 30, 22000, 733),
('ps-seasonal-1-3', 'seasonal', 1, 3, 25, 22000, 880),
('ps-seasonal-1-4', 'seasonal', 1, 4, 25, 22000, 880),
('ps-seasonal-2-1', 'seasonal', 2, 1, 25, 20000, 800),
('ps-seasonal-2-2', 'seasonal', 2, 2, 25, 20000, 800),
('ps-seasonal-2-3', 'seasonal', 2, 3, 20, 20000, 1000),
('ps-seasonal-2-4', 'seasonal', 2, 4, 20, 20000, 1000),
('ps-seasonal-3-1', 'seasonal', 3, 1, 20, 18000, 900),
('ps-seasonal-3-2', 'seasonal', 3, 2, 20, 18000, 900),
('ps-seasonal-3-3', 'seasonal', 3, 3, 15, 18000, 1200),
('ps-seasonal-3-4', 'seasonal', 3, 4, 15, 18000, 1200);

-- Veteran staff
INSERT OR IGNORE INTO productivity_standards (id, staff_type, staff_level, product_group, orders_per_hour, cost_per_hour, cost_per_point) VALUES
('ps-veteran-1-1', 'veteran', 1, 1, 40, 24000, 600),
('ps-veteran-1-2', 'veteran', 1, 2, 35, 24000, 686),
('ps-veteran-1-3', 'veteran', 1, 3, 30, 24000, 800),
('ps-veteran-1-4', 'veteran', 1, 4, 30, 24000, 800),
('ps-veteran-2-1', 'veteran', 2, 1, 35, 22000, 629),
('ps-veteran-2-2', 'veteran', 2, 2, 30, 22000, 733),
('ps-veteran-2-3', 'veteran', 2, 3, 25, 22000, 880),
('ps-veteran-2-4', 'veteran', 2, 4, 25, 22000, 880),
('ps-veteran-3-1', 'veteran', 3, 1, 30, 20000, 667),
('ps-veteran-3-2', 'veteran', 3, 2, 25, 20000, 800),
('ps-veteran-3-3', 'veteran', 3, 3, 20, 20000, 1000),
('ps-veteran-3-4', 'veteran', 3, 4, 20, 20000, 1000);
