#!/bin/bash
# Quick generate 730 days of orders (smaller dataset for MVP)
# Average 500 orders/day = ~365,000 total orders

cd /home/user/webapp

echo "🚀 Generating 730 days of order data..."
echo "📊 Target: ~365,000 orders (avg 500/day)"
echo ""

# Create SQL file
cat > /tmp/bulk-orders.sql << 'EOFHEADER'
-- Bulk insert orders for 730 days
-- Generated by quick-generate-orders.sh

EOFHEADER

# Marketplaces array
MARKETPLACES=("Shopee" "Lazada" "TikTok Shop" "Tiki" "Sendo")
CARRIERS=("GHTK" "Ninja Van" "Viettel Post" "GHN" "J&T Express")
SERVICE_LEVELS=("fast" "express" "same_day" "economy" "bulky")

# Peak day multipliers (simplified)
declare -A PEAK_DAYS
PEAK_DAYS["01-02"]="3.5"
PEAK_DAYS["02-02"]="2.8"
PEAK_DAYS["03-03"]="2.6"
PEAK_DAYS["04-04"]="2.5"
PEAK_DAYS["05-05"]="2.7"
PEAK_DAYS["06-06"]="3.2"
PEAK_DAYS["07-07"]="2.9"
PEAK_DAYS["08-08"]="3.0"
PEAK_DAYS["09-09"]="3.8"
PEAK_DAYS["10-10"]="3.5"
PEAK_DAYS["11-11"]="4.2"
PEAK_DAYS["12-12"]="3.9"

TOTAL_ORDERS=0
BATCH_SIZE=100

# Generate for last 730 days
for i in $(seq 729 -1 0); do
  DATE=$(date -d "$i days ago" +%Y-%m-%d)
  DAY_OF_MONTH=$(date -d "$i days ago" +%d)
  MONTH=$(date -d "$i days ago" +%m)
  MM_DD="${MONTH}-${DAY_OF_MONTH}"
  
  # Check if peak day
  MULTIPLIER=1.0
  if [[ -n "${PEAK_DAYS[$MM_DD]}" ]]; then
    MULTIPLIER="${PEAK_DAYS[$MM_DD]}"
  fi
  
  # Weekend bonus
  DAY_OF_WEEK=$(date -d "$i days ago" +%u)
  if [ $DAY_OF_WEEK -eq 6 ] || [ $DAY_OF_WEEK -eq 7 ]; then
    MULTIPLIER=$(echo "$MULTIPLIER * 1.3" | bc)
  fi
  
  # Calculate order count
  BASE_ORDERS=500
  ORDER_COUNT=$(echo "$BASE_ORDERS * $MULTIPLIER * (0.9 + RANDOM % 20 / 100.0)" | bc | cut -d'.' -f1)
  
  # Generate orders for this day
  echo "INSERT INTO orders_history (id, order_id, order_date, order_time, fulfillment_center_id, customer_id, marketplace, product_group, sku_complexity, service_level, shipping_carrier, num_items, is_delayed_allowed) VALUES" >> /tmp/bulk-orders.sql
  
  for j in $(seq 1 $ORDER_COUNT); do
    ORDER_ID="ORD-${DATE//-/}-$(printf '%06d' $j)"
    UUID=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || echo "$(date +%s)-$RANDOM-$j")
    HOUR=$(printf '%02d' $((RANDOM % 24)))
    MINUTE=$(printf '%02d' $((RANDOM % 60)))
    
    # Random selections
    MARKETPLACE_IDX=$((RANDOM % 5))
    MARKETPLACE="${MARKETPLACES[$MARKETPLACE_IDX]}"
    
    SERVICE_IDX=$((RANDOM % 5))
    SERVICE_LEVEL="${SERVICE_LEVELS[$SERVICE_IDX]}"
    
    CARRIER_IDX=$((RANDOM % 5))
    CARRIER="${CARRIERS[$CARRIER_IDX]}"
    
    PRODUCT_GROUP=$((1 + RANDOM % 4))
    NUM_ITEMS=$((1 + RANDOM % 5))
    
    COMPLEXITY=("simple" "medium" "complex")
    COMPLEXITY_IDX=$((RANDOM % 3))
    SKU_COMPLEXITY="${COMPLEXITY[$COMPLEXITY_IDX]}"
    
    IS_DELAYED=0
    if [ "$SERVICE_LEVEL" = "economy" ]; then
      IS_DELAYED=1
    fi
    
    # Last row check
    if [ $j -eq $ORDER_COUNT ]; then
      COMMA=";"
    else
      COMMA=","
    fi
    
    echo "('$UUID', '$ORDER_ID', '$DATE', '$HOUR:$MINUTE:00', 'FC-HCM-01', 'CUST-$((1 + RANDOM % 100))', '$MARKETPLACE', $PRODUCT_GROUP, '$SKU_COMPLEXITY', '$SERVICE_LEVEL', '$CARRIER', $NUM_ITEMS, $IS_DELAYED)$COMMA" >> /tmp/bulk-orders.sql
  done
  
  echo "" >> /tmp/bulk-orders.sql
  
  TOTAL_ORDERS=$((TOTAL_ORDERS + ORDER_COUNT))
  
  # Progress every 30 days
  if [ $((i % 30)) -eq 0 ]; then
    echo "📅 Processed $(date -d "$i days ago" +%Y-%m) - Total orders: $TOTAL_ORDERS"
  fi
done

echo ""
echo "✅ Generation complete!"
echo "📊 Total orders generated: $TOTAL_ORDERS"
echo "📄 SQL file: /tmp/bulk-orders.sql"
echo "📦 File size: $(du -h /tmp/bulk-orders.sql | cut -f1)"
echo ""
echo "🔄 Loading into database..."
wrangler d1 execute boxme-forecast-production --local --file=/tmp/bulk-orders.sql

echo ""
echo "✅ Done! Verifying..."
wrangler d1 execute boxme-forecast-production --local --command="SELECT COUNT(*) as total_orders FROM orders_history"
